sudo: required
services:
  - docker

before_install:
  - docker build -t stiw47/docker-react -f Dockerfile.dev .

script:
  - docker run stiw47/docker-react echo All good!

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-central-1-654654537494"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
