name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag docker-react
    
    - name: Run Docker container
      run: docker run -d --name docker-react docker-react
    
    - name: Run arbitrary code inside the container
      run: docker exec -it docker-react echo Hello
